# Generated by Django 5.1.3 on 2025-01-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendant',
        ),
    ]
