# Generated by Django 4.2.7 on 2025-02-14 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("backendapi", "0002_delete_attendant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attendant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=30)),
                ("last_name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=100)),
                ("phone_number", models.CharField(max_length=12)),
            ],
        ),
    ]
