# Generated by Django 4.2.7 on 2025-02-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backendapi", "0004_attendant_crew_attendant_discord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendant",
            name="crew",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="attendant",
            name="ticketCrewID",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
