# Generated by Django 5.1.5 on 2025-02-20 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backendapi", "0005_alter_attendant_crew_alter_attendant_ticketcrewid"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Attendant",
        ),
    ]
